spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git: https://github.com/xhh1314/springcloudshop
        search-paths: configserver/src/main/resources/shared
      label: dev
server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/