spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:/shared

  profiles:
    active: native
server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/