#spring:
#  application:
#    name: configserver
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/xhh1314/springcloudshop
#          search-paths: configserver/src/main/resources/shared
#      label: dev
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
          default-label: dev

  profiles:
    active: native
server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/